import sys
import os
import subprocess
import json
import argparse
from datetime import datetime

def run_cmd(cmd, description):
    print(f"\n>>> {description} <<<")
    print(f"CMD: {' '.join(cmd)}")
    try:
        subprocess.check_call(cmd)
        print(">> SUCCESS")
    except subprocess.CalledProcessError:
        print(">> FAILED")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--fast", action="store_true", help="Run in fast mode (skip heavy robustness sweep, run smoke test instead)")
    parser.add_argument("--dev", action="store_true", help="Run in dev mode (reduced robustness sweep)")
    parser.add_argument("--full", action="store_true", help="Run full robustness sweep (all windows)")
    args = parser.parse_args()
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    print(f"=== Nightly Model Healthcheck [{timestamp}] ===")
    
    # 1. Verification / Smoke Tests
    print("\n[Phase 1] Verification Tests")
    run_cmd([sys.executable, "-m", "unittest", "tests/test_tail_calibrator_inventory.py"], "Checking Calibrators")
    
    robustness_meta = None
    
    # Determine mode
    if args.fast:
        print("\n[Fast Mode] Skipping Full Robustness Sweep. Running Smoke Test.")
        run_cmd([sys.executable, "-m", "unittest", "tests/test_production_profile_smoke.py"], "Production Profile Smoke Test")
    else:
        # Logic: If --dev is set, use dev mode. If --full is set (or neither), use full mode.
        # But if both are set? Prefer dev for safety? Or full?
        # Typically flags override each other. Let's say if --dev, then dev. Else if --full, full. 
        # If neither, default to full (as per original script behavior) or maybe require explicit flag?
        # Original behavior: without --fast, it ran full sweep (unless --dev was passed).
        # We will keep that: default is full sweep if not fast.
        
        print(f"\n[Phase 2] Robustness Sweep & Regression Gate")
        sweep_cmd = [sys.executable, "scripts/run_robustness_sweep.py"]
        
        if args.dev:
            print("(Mode: Dev - 7 Day Window)")
            sweep_cmd.append("--dev")
        elif args.full:
             print("(Mode: Full - All Windows)")
             # No extra arg needed for full, it's default in sweep script
        else:
             print("(Mode: Default/Full - All Windows)")

        run_cmd(sweep_cmd, "Running Robustness Sweep")
        
        # Load metadata generated by sweep
        if os.path.exists("outputs/eval/latest_robustness_run.json"):
            with open("outputs/eval/latest_robustness_run.json", 'r') as f:
                robustness_meta = json.load(f)
        else:
            robustness_meta = None

    # 2. Update LATEST.md
    print("\n[Phase 3] Updating LATEST.md")
    latest_md_path = "outputs/eval/LATEST.md"
    
    try:
        with open(latest_md_path, 'w') as f:
            f.write(f"# NHL Model Status: {timestamp}\n\n")
            
            if robustness_meta:
                scope = robustness_meta.get('scope', 'unknown')
                f.write(f"## Recent Robustness Run ({scope})\n")
                f.write(f"- **Timestamp:** {robustness_meta['timestamp']}\n")
                f.write(f"- **Leaderboard:** [View]({os.path.basename(robustness_meta['leaderboard'])})\n")
                f.write(f"- **Regression Gate:** [View]({os.path.basename(robustness_meta['gate_report'])})\n")
                f.write(f"- **Prod Table:** `{robustness_meta['prod_table']}`\n")
                f.write(f"- **Baseline Table:** `{robustness_meta['baseline_table']}`\n")
            else:
                if args.fast:
                    f.write("## Robustness Run\n")
                    f.write("*Skipped (Fast Mode)*. See Smoke Test logs.\n")
                else:
                    f.write("## Robustness Run\n")
                    f.write("ERROR: No metadata found. Sweep may have failed.\n")
                    
            f.write("\n## Quick Links\n")
            f.write("- [Regression Gate Script](../../scripts/check_regression_gate.py)\n")
            f.write("- [Production Profile](../../config/production_profile.json)\n")
            f.write(f"- [Latest Logs](../../outputs/logs/)\n")
        
        print(f"Updated {latest_md_path}")
    except Exception as e:
        print(f"Error updating LATEST.md: {e}")
        # Don't fail the build just for the MD update, but good to know
    
    print("\n=== Healthcheck Complete ===")

if __name__ == "__main__":
    main()